### ISSUE TITLE
Game Does Not Launch

### ISSUE THREAD

**Issue by nicholasderk** [Nibre/MotherVR#10]
I had AI opening in stereo before, I added the DLL and now it will say Running in Steam for a few seconds before nothing further happens. Now when I remove the DLL the game does the same behaviour unless I switch the ENGINE_SETTINGS for hack to Off, and then it'll start in non-stereo. But if I add Rift back into the file, it goes back to failure to launch.

**Comment by duig0** [comment]
Pretty much the same as issue #7

https://github.com/Nibre/MotherVR/issues/7

**Comment by otraupe** [comment]
Oculus Home has to be installed and run in order for AI to start correctly in VR. At least for me. I believe this was different back in the day with the DK2.

**Comment by Nibre** [comment]
Are you still having these problems with the latest release?

**Comment by Nibre** [comment]
I'll close this for now, but you can still respond if you need to.
