### ISSUE TITLE
Menu UI can appear off-screen

### ISSUE THREAD

**Issue by baggyg** [Nibre/MotherVR#14]
I know this one was mentioned under release issues. For me this would seem to be one of the only remaining issue that wasn't actually present in the DK2 playthrough. This is the only one actually holding me up going back in at the moment. Is it likely this will be a simple / quick fix? 

(P.s. It was worth noting that when I loaded a save game I had previously I did see the save game dialog when interacting with a telephone. This may not be as large a problem as I expect - I am very near the start so not sure how important these are but I don't know the button combinations)

**Comment by Nibre** [comment]
HUD and Menu have been rescaled and repositioned, so this issue should be good now.
