### ISSUE TITLE
Did something stupied tried select oculus start with pimax

### ISSUE THREAD

**Issue by Skidrow68** [Nibre/MotherVR#181]
Tried select oculus start with pimax when game is installed on steam and now they game will not start at all what ever i do with mother vr.

**Comment by Skidrow68** [comment]
Were is the information with vr system you have saved? tried repacing the dxgi.dll but that dont help.

**Comment by Bluscream** [comment]
Start it with `AI.exe -steamvr`

**Comment by Skidrow68** [comment]
Thank you Bluscream now the game starts again now i just need to figure out what to do :)

**Comment by Bluscream** [comment]
Please close the issue if we're done here ;)
