### ISSUE TITLE
Crafting with Mouse/Keyboard: how to?

### ISSUE THREAD

**Issue by otraupe** [Nibre/MotherVR#19]
As the mouse pointer isn't there, how do you activate the actual crafting process after you selected the components? I can't find a way to reach the button via the movement keys.

This was the same back in the day, but there was at least the mouse pointer.

However, otherwise crafting has been fully repaired! Back then the final crafting button was right in the middle between the left and right eye for me, in an invisible section of the display.

**Comment by Lurkstrober** [comment]
Seconded! I'm finding playing with the KB/M is the way to go for me but can't craft (no mouse pointer to click the button and no way to get there using the movement keys).

**Comment by Pesm** [comment]
Same problem for me.

**Comment by Timjfjdd** [comment]
also an issue here.... :/

**Comment by MulleredOG** [comment]
Play with a pad ;)

**Comment by otraupe** [comment]
Yeah, great idea! :)

Not. I'd rather cut myself 3 fingers off than playing with such a broken thing.

**Comment by schmorgy** [comment]
As a workaround, is it possible to bind a key to the craft item box using the input.cfg file?  If it can be selected with the joypad, surely it can be bound to a key?

**Comment by Nibre** [comment]
This has been fixed in the latest [Release](https://github.com/Nibre/MotherVR/releases)
