### ISSUE TITLE
Feature Request - Steam VR disable wand/vr controller input (related to WMR controller bugs)

### ISSUE THREAD

**Issue by tri-bit** [Nibre/MotherVR#199]
I tried AI Mother 0.8 on my Reverb G2 WMR controllers and I'm trying to play with keyboard + mouse only but the controller inputs are spamming randomly as well and making it impossible to play. (I've played through the game twice on occulus - keyboard + mouse only.) 
Would love a toggle/disable option for steam vr controller input (so we can still play using any future HMDs)
Update: This occurs even if the game is booted without turning on the G2 controllers.

**Comment by Bluscream** [comment]
You can use third party steamvr drivers to disable controller input

**Comment by blord86** [comment]
Fixed on 0.8.1 version.

**Comment by tri-bit** [comment]
I've tested and confirmed it's working - I can play keyboard + mouse with G2 HMD. Thank you Nibre!
