### ISSUE TITLE
Can't use gamepad anymore with 0.8.0 / vr controller always forced

### ISSUE THREAD

**Issue by Hoshi82** [Nibre/MotherVR#202]
The game completely bugs out when using gamepad and not having vr controller on, because I don't want to use them. Some inputs are constantly triggered and resulting in you always go into crouching and swinging your hammer. Also button overlays only show vive wands inputs not the xbox game pad button promps.

**Comment by lunzueta** [comment]
I have the same problem with Rift S when I just want to use only the XBox 360 controller as input and no Rift S controllers active.

**Comment by Nibre** [comment]
Does this new version make any difference?

https://github.com/Nibre/MotherVR/releases

**Comment by Hoshi82** [comment]
> 
> 
> Does this new version make any difference?
> 
> https://github.com/Nibre/MotherVR/releases

The new version fixed it for me. Thanks! :)

**Comment by lunzueta** [comment]
It worked for me too. Thank you!
