### ISSUE TITLE
Works with Oculus Link in Epic Games, but not with Virtual Desktop VR in Oculus Quest 2 (WiFi)

### ISSUE THREAD

**Issue by juampe** [Nibre/MotherVR#208]
With Oculus Quest 2
I can play many VR games via WiFi with Vitual Desktop 1.18.8 SteamVR mode.
I can play Alien Isolation via oculus link (usb cable) and MotherVR 0.8.1.

I was Trying to start the game with MotherVR 0.8.1 via Virtual Desktop 1.18.8 with SteamVR 1.16.1 beta (SteamVR now passes all OpenXR 1.0 conformance tests on Windows for Vulkan, OpenGL, D3D11, and D3D12)
```
Failed to initialize Oculus!
[ovr_Create: No HMD attached. | -1007]`

Look into the avobe error, and try again once it has ben resolved.

Mother VR will now start with VR disabled. Resrtart the game to try again.
```

**Comment by Bluscream** [comment]
Looks like MVR is trying to use Oculus not steamvr there, try switching it to steamvr when connected with link, close the game, start steamvr with Virtual Desktop and restart your game

**Comment by juampe** [comment]
Ok, you are right, I had to switch the openxr runtime to steamvr. Now AI works with WiFi!. Thanks a lot.

**Comment by Bluscream** [comment]
Np ^^

**Comment by BimpArno** [comment]
my steamVR is on openxr how do i play this on wifi.. still not clear to me

**Comment by Bluscream** [comment]
![](https://forums.flightsimulator.com/uploads/default/original/4X/c/a/b/cabad6fddb2d5cb2d4cd98f29bebfdeb943ec4e5.jpeg)

**Comment by BimpArno** [comment]
![image](https://user-images.githubusercontent.com/34709397/174470922-c38bd2ed-a179-4ce7-b12c-0a0fb226bcb9.png)
i have that setting on steamVR

**Comment by BimpArno** [comment]
YES!!! got it working now
in the game in oprions use steamVR
