### ISSUE TITLE
Aiming over the iron sights is nearly impossible

### ISSUE THREAD

**Issue by otraupe** [Nibre/MotherVR#21]
Any way to have the view point aligned with the gun?

**Comment by otraupe** [comment]
@Nibre, does labeling this as "legacy vr bug" mean this can likely not be fixed?

**Comment by Nibre** [comment]
Nah, just means that it's not something that I messed up, the old VR already had the same problem. It may be able to be fixed, but it's low on the list of things.

**Comment by otraupe** [comment]
Great, thanks!

**Comment by Nibre** [comment]
Release 0.4.0 should resolve this, as you can now (mostly) see where you're aiming. I'm going to mark this as closed, and will probably create a separate issue later on for improving the reticle beyond it being a flat symbol on the HUD. 

Let me know if this new release helps at all 👍
