### ISSUE TITLE
Loading Save file not working

### ISSUE THREAD

**Issue by EnderWolfC** [Nibre/MotherVR#220]
I have been trying to play Alien Isolation in VR using this mod. I own a copy of the game on epic games and use the oculus quest through link everything seems to work amazingly except it won't let me load save files or click continue game. It makes me restart the game every time I want to play. When I play without the VR mode on it will let me continue the game or load saves but it won't let me in VR. When I try to load or continue in VR the buttons are grey and unhighlighted as if there is not anything saved. I really do like the mod and think you did an amazing job of it so I would be very grateful if you help me to fix this issue.

**Comment by Godnnelg** [comment]
EnderWolfC - I run the game via EpicGames through SteamVR (imported the game in Steam) and I use SteamVR to play it in VR; I'm not having any problems saving and loading a saved game here. Have you tried reinstalling the game and the plugin?

**Comment by EnderWolfC** [comment]
Thanks Godnnelg, It worked once I ran it through steam VR instead of straight through oculus link.

**Comment by goooroooX** [comment]
Is there any way to load game with Oculus runtime? This is really annoying limitation.

**Comment by seymop** [comment]
So......I am having the same exact issues as Enderwolf.  Same scenario as well. I tried Godnnelg's suggestion and it did not work.  Still unable to load the game and it completely changed the control scheme of the Oculus controllers which is no good.

Any other suggestions at this point would be greatly appreciated.
