### ISSUE TITLE
Additional Steam apps start during play & this crashes ai.exe

### ISSUE THREAD

**Issue by ajpenn** [Nibre/MotherVR#25]
Happens when using xbox controller. Particularly when hitting A button when entering vents. Only fix I can find is to either delete or rename other Steam games in steamapps folder (though Steam reinstalls game folder for other games in steamapps on restart). Love AI VR, but this is a major headache.

**Comment by baggyg** [comment]
Do you have Steam Big Picture or Steam VR running?

**Comment by Nibre** [comment]
Are you still having this problem with the latest release?

**Comment by ajpenn** [comment]
Sorry I didn't reply, I was in hospital for an unplanned operation. Your advice resolved the issue - (steam vr caused the problem), thanks. Thanks also as it's terrific being able to play this on the Rift! 

I've been wondering if you could do the same for Dying light - a great game that was also built with VR support that was removed for CV1? One of the reasons I bought the Rift was to play it, only to be dissapointed. I imagine I'm not alone.

**Comment by baggyg** [comment]
The devs actually put Dying Light support back in themselves. It has its problems but is certainly playable already on Rift

**Comment by ajpenn** [comment]
Didn't realise they'd put it back - brilliant! Many thanks.
