### ISSUE TITLE
What kind of VR headsets work?

### ISSUE THREAD

**Issue by Ziemniak44** [Nibre/MotherVR#250]
Im very intrested in buying myself a VR headset to play this mod but I dont know which ones are compatible. Would a rift S work just fine? or do you need one of the newer headsets?

**Comment by MulleredOG** [comment]
Pretty much any modern headsets that work on Steam VR will work. A rift S should still work. In fact the MotherVR mod can also use the Oculus runtime. If you wanted to buy something a new a Quest 2 or 3 would be your best bang for buck options. Just beware this mod is now somewhat broken, and there are some rendering issues, particularly when running at higher resolutions. The mod has long been abandoned so it is unlikely that there will be any fixes anytime soon

**Comment by Ziemniak44** [comment]
Alright, thanks👍
