### ISSUE TITLE
Sometimes  hud menu don't follow the view

### ISSUE THREAD

**Issue by netshaman** [Nibre/MotherVR#26]
When playing in survival mode and in endurance mode  the "B" menu is not displayed at the right place , but at the last place it was opened before !
If you open it at a new place , it still stays where it was .
For example if i 'm looking at a window and open the map menu , then if i walk away from this place and open the craft menu , this one is displayed in front of the window whaere i was before, i need to re-open the map menu to refresh it and force it to be displayed where i'm currently .
This is particularly annoying when looking at a crate , door or object , because nothing is displayed to help you know what is the thing you are looking at.

**Comment by duig0** [comment]
???

**Comment by netshaman** [comment]
Sorry , an error has occured when i was writing..

**Comment by duig0** [comment]
Oh okay....sorry i cant help with the issue though :-(. Did you try the updated dll?

**Comment by netshaman** [comment]
i' m using the 0.2 version at the moment , is there a newer version that i don't know ?

**Comment by StarLightPL** [comment]
still exists in 0.3.0.1

**Comment by pinoepel** [comment]
I have this bug too, since first start of a fresh install with steam

**Comment by blord86** [comment]
This problem also happened before Nibre's mod, I remember seing it when I played the game with native VR support on my DK2 a couple of years ago. Not sure if Nibre can fix it, but I would say he can, given that his mod is more a hack than a mod. At the moment, the only way to fix it is to completely exit the game and enter again.

**Comment by Nibre** [comment]
This is now fixed in the latest [Release](https://github.com/Nibre/MotherVR/releases)
