### ISSUE TITLE
After intro videos "AI.exe has stopped working"

### ISSUE THREAD

**Issue by chieflukas** [Nibre/MotherVR#27]
Happens every time as soon as it's about to get to the main menu.
I'm running alpha 2.0
-novr mode works and removing the dll also works but still: The VR mod doesn't work for me.

Thanks for any help

EDIT: Trying clean reinstall ATM
EDIT 2: No luck
EDIT 3: Got it to work, you have to launch in your OCULUS HOME, it appears there

**Comment by D3fcon5** [comment]
Hi, same here! dunno what to try next!

**Comment by chieflukas** [comment]
Read the 3rd edit D3fcon5, hope it helps

**Comment by D3fcon5** [comment]
the first time it tried your solution I came at least to the main Menu. But after starting the game all was black and I just could get the Map out...now I have the same problem again. not even the Main Menu

**Comment by nikor30** [comment]
Have the same issue, sometimes rashes menus but never able to launch game. also tried alpha 0.11 same here.
