### ISSUE TITLE
Image is skewed and the entire depth is only at an arms length

### ISSUE THREAD

**Issue by hundenmarvin** [Nibre/MotherVR#29]
I have this weird skewing issue. It's like I'm sitting at a theater on the front row furthest to the right so the entire cinema screen gets all skewed. The right side of the image is much bigger than the left side. It's worst in the menus and videos but in-game is also skewed somewhat. The stereo depth in-game is extremely short, like an arms length. What's peculiar is that the image is not skewed in the SteamVR-headset-mirror-view on my desktop. chaperone also shows up correct inside the hmd.

I have tried all versions of the mod, I have tried recentering my view with the bumpers, switched between fullscreen and windowed, switching fov in settings, tried both with and without "-openvr" in launch options. Nothing changes.

I am a revive user by the way but I haven't heard anyone else having this issue using revive. I might as well share my specs if it should help:
Windows 10 64 bit, nvidia driver 382.05, i7-6700k, 16gb, gtx1080ti.

It would be so awesome if I could get this mod to work on my computer.

**Comment by baggyg** [comment]
I believe the general instruction at the moment is this is not compatible with Revive. Nibre is trying to get native OpenVR supported for Vive users.

**Comment by hundenmarvin** [comment]
Ok, I will wait for vive support then :-)

**Comment by Nibre** [comment]
Vive support is now on this newest release. Use `-steamvr` to enable it.
