### ISSUE TITLE
Vive support

### ISSUE THREAD

**Issue by steren** [Nibre/MotherVR#3]
Thanks so much for creating this mod. I suggest to open Issues to track feature availability. 

As I am waiting for a Vive support. I will be watching this thread.

**Comment by Armada651** [comment]
@Nibrr I don't know how far along with Vive support you are yet, but if you upload the source I can probably help out a bit.

**Comment by StarLightPL** [comment]
@Armada651 The source code is included with the release https://github.com/Nibre/MotherVR/releases/tag/0.1.1

**Comment by Armada651** [comment]
@StarLightPL If that were the case I wouldn't be asking, as you may know the source code links there are just the contents of the github repo. And currently this github repo only contains a ReadMe.

**Comment by StarLightPL** [comment]
@Armada651 I'm very sorry I just saw it included, didn't actually click on link :( Well it's up to @Nibre to decide then.

**Comment by Nibre** [comment]
No worries, we're working on it 👍

**Comment by dankennard** [comment]
Another one here, chomping at the bit to help out with Vive compatibility.

**Comment by Skidrow68** [comment]
When i added dxgi.dll to Alien Isolation directory the game crash as it should start to show first "movie" and if i remove it the game starts.

**Comment by Nibre** [comment]
Vive support is now on this newest release. Use `-steamvr` to enable it.
