### ISSUE TITLE
Game crashing intermittantly .. and an odd bug

### ISSUE THREAD

**Issue by SparkieShock** [Nibre/MotherVR#30]
Been playing with MOTHER VR 2.0 of Alien Isolation .. at the point in the game where I'm at the seegson communications. However my game has crashed several times along the way. Hard to say what caused it. I have a PC with an i75960X CPU, 3 X Titan X's, and 64 Gigs of RAM .. so I can't believe I'm running out of power? (I'm a 3D artist .. so my render rig makes an AWESOME oculus gaming machine).

Anyways .. just thought I'd mention it.

Also .. the odd bug .. is where the Damaged Seegson Android tries to grab you in the small cafeteria there are NO options to break free from it's grasp .. no button on the xbox controller would let me out .. and the game crashed just after this point too.

Other than that it's been DAMNED AWESOME playing this game .. finally .. in VR.

**Comment by Nibre** [comment]
Are you still having this problem with the latest release?

**Comment by SparkieShock** [comment]
I have had it a few times .. It’s hard to say why or when it happens. My computer is a real beast of a machine so it should be able to handle the graphics and oculus needs:

i7 5960X CPU
64 Gigs RAM
3 x Titan X (Maxwell) - 2 in SLI mode

I do 3D art (naughty graphic novel porn :D) and animations so my render rig is designed for high graphic potential .. which makes playing Oculus titles VERY slick indeed.

Another problem I had is that the first time I came to a working joe that was lying on the floor .. it grabbed me but there were no options to fight it and make it loose it’s grip. With the keyboard one typically just hits the ‘use’ button until Ripley hits it with the wrench .. but in Oculus mode there are no options to do this … so I die .. and can’t continue the game any further. I was waiting to see if you would release an updated DLL that would hopefully address this issue too.

Awesome work though I have to say. It is REALLY awesome to be able to play this game with VR. Haven’t even had an encounter with the Alien yet … no properly anyways .. but it’s so good. Anyways, I assume you’ve made a new release so I’ll look it up and try it out tonight.

Thanks again for your efforts on enabling VR mode, I’ll give it another go and let you know how I fair.

Sparkie

**Comment by otraupe** [comment]
Maybe your 3 Titan X are getting bored by having nothing todo and have started chatting in the bg making the game wait for'em....

**Comment by NeonUniverse** [comment]
Could be due to the Titans being in 3-way SLI, which I personally know causes issues with VR. Try removing one of the Xs and see if that solves it, or disable it some other way that wont break SLI. I have 2 GTX 1080s in SLI and it works fine.

**Comment by Nibre** [comment]
The button prompt issue is fixed in the latest [Release](https://github.com/Nibre/MotherVR/releases)

**Comment by Nibre** [comment]
If you still have crashing problems with this latest release, you can respond to reopen this.
