### ISSUE TITLE
Crash on startup/nothing

### ISSUE THREAD

**Issue by SanyaZ** [Nibre/MotherVR#35]
So Im using the vive, got Steamvr started and all. I Put the files in the main dictionary. So if I start it I get some OSVR error shit and oculus opens but I dont use it only for Revive. Anyway. 
If I add -steamvr in the launch it just sits there and does nothing and not even launch
I'm at a loss here.

**Comment by hyperion6000** [comment]
exact same issue for me

**Comment by Nibre** [comment]
So the Alien window pops up and just closes? Doesn't crash?
Are you on 0.3.0.1? And both `dxgi.dll` and `openvr_api.dll` are in the Alien folder?
I would maybe try restarting your computer, just to rule out some potential problems.

**Comment by hyperion6000** [comment]
The steam lunch window for alien pops up for a while then dissapeirs without a trace, not even a process to end. I'm using 0.3.01 and both files are in the main alien folder(with the .exe. I restarted my PC multiple times and game works fine when I launch it in non-vr mode. Thankyou for your time and help 😃

**Comment by Nibre** [comment]
If it is actually crashing, then this program should be able to grab a crash dump for me from it.

If you want, you can try downloading ProcDump from Microsoft (which can be found [here](https://download.sysinternals.com/files/Procdump.zip)). Extract it, then create a *.txt file in the same folder, copy `.\procdump.exe -e -h -w -s 3 AI.exe /accepteula & pause` into it, save it, and then rename the *.txt file to `alien_debug.bat`. 

Double click on the .bat, and it should say 'Waiting for process named AI.exe...'. So then you start up Alien, and if it crashes, this program should create a `AI.exe_170827_XXXXXX.dmp` file that I can inspect.

Try it out, and just let me know if it makes a *.dmp file or not.

**Comment by hyperion6000** [comment]
Thanks for the help Nibre, I will do this tomorrow(its late at night here is Australia) and let you know how it goes.

**Comment by ElectricZ** [comment]
Hi Nibre,

Having the same issue outlined above and was able to capture a dump file. (attached). Thanks for your hard work! 
[AI.exe_170827_084808.dmp.zip](https://github.com/Nibre/MotherVR/files/1254429/AI.exe_170827_084808.dmp.zip)

**Comment by DarianWolf** [comment]
I have the same problem, uploaded my crashdump file. This is on windows 7 x64 with procdump64.exe, strangely it tries to launch it in theater mode before crashing/giving up.
[AI.exe_170827_180159.zip](https://github.com/Nibre/MotherVR/files/1254515/AI.exe_170827_180159.zip)

**Comment by CuriousRddit** [comment]
If you want to play, you can try couple of things.

1. In steam, go into the game properties and disable "Use Desktop game theater while in steamvr..." I disabled this and it worked with steamvr for me

2. If above does not work then close steam vr and launch game independently and it will run in "openvr"

**Comment by gitfat** [comment]
I was also having the same problem. To fix it, I ended up having to start the game in -novr mode (enter -novr in the game's launch options on steam) then set it to windowed mode, then restarted the game with -steamvr to make it work on the vive.

**Comment by SanyaZ** [comment]
CuriousRddits fix works.. Sorry for not responding If theres something I should try Nibre please tell me.

**Comment by Nibre** [comment]
It's the `Use Desktop Game Theatre while SteamVR is active` that's doing it. I think I've found a way to fix it, so that should be in the next update. For now, just make sure Theatre is unchecked and it should work.

**Comment by JulsIII** [comment]
Even with "Use Desktop  Game Theater while SteamVR is Active" is unchecked and even with windowed mode and various resolutions I'm still getting the problem. Crash everything without fail. I don't think it's due to the Theater - problem still exists with it unchecked.

**Comment by JulsIII** [comment]
Non of these fixes are working for me. I have "Use Desktop Theatre" off. I've tried windowed and non windowed modes and in various resolutions. Not fixed - I'll keep trying different stuff out.

**Comment by Squidboy30** [comment]
Hi, i get an Ai.exe crash at startup. I have tried all the above suggestions. One thing of difference to note is that i am using windows mixed reality headset. I have captured the crash dump log. Hope that helps. This mod does look very cool indeed....cant wait to try it out.

[AI.exe_171201_122339.dmp.zip](https://github.com/Nibre/MotherVR/files/1521588/AI.exe_171201_122339.dmp.zip)

**Comment by Nibre** [comment]
Can you guys try this again on the new release, and let me know if it changed anything? Thanks

**Comment by Squidboy30** [comment]
Hi Nibre, I am very pleased to say you nailed it. Working with a windows HMD...

**Comment by NeonUniverse** [comment]
Fixed as of new release, cheers Nibre <3
