### ISSUE TITLE
Super Sampling (Lighting Different for either eye)

### ISSUE THREAD

**Issue by baggyg** [Nibre/MotherVR#37]
I realise this is probably out of the scope of getting the previous integration working. I tried AI with 1.8 Super Sampling (worth noting Oculus Tray Tool profile doesn't work - you need to set the global setting).

It is evident there are some shadows that show differently in each eye. Its almost as if one eye sees things slightly darker. You can live with it - but though I would mention. 

The biggest issue is that the map does not show. When you press the 'select' key the menu pops up but you don't see anything. Pressing the X button to switch between floors crashes the game. 

0.3.0.1 is otherwise working great for me... can alt tab in and out of the game with no problem.

**Comment by MulleredOG** [comment]
I cant set super sampling any higher than 1.3 without seriously affecting my performance, gtx 980ti + 2600k @ 4.3ghz

**Comment by baggyg** [comment]
1.8 ran fine for me although I think there a few dips to 45 ASW. GTX 1080ti + i7 4790.
Its harder to notice without motion controllers. It did look lovely at 1.8 although probably not as much as a jump in quality as I see in other games. 

I may try a lower setting and see if I get the same map issues. When you tried 1.3 could you see the map and switch floors?

**Comment by MulleredOG** [comment]
I can go a bit higher, and although it appears smooth I can see visual artefacts which suggest the ASW is kicking in heavily. I hardly use the map so I dont know whether your issue is present for myself, I've certainly not noticed anything.  I'll have a look next time I play

**Comment by baggyg** [comment]
Thanks that would be helpful to determine if it is a problem with SS or something else.

**Comment by baggyg** [comment]
Re-tried today and I couldn't replicate my main problem. The map is back and no crashes switching between floors. Considering on my playthrough I was alt tabbing out to the OTT and trying other things I suspect I actually did something else to cause this to happen. Therefore no crashing here. 

The only remaining issue is the lighting appearing differently in both eyes. Would the volumetric lighting setting or something similar have an affect here?

@MulleredOG I had a play with the performace tool through OTT. The game does move down to 45 ASW almost constantly with a higher SS. However try switching ASW off. With this switched off I had a pretty much constant 90 and smooth even at higher values.

**Comment by baggyg** [comment]
In fact the performance headroom didn't change at all for me... 1.4 showed the same performance as 1.8

**Comment by Nibre** [comment]
That's might be because your SSAO is set to 'Standard'. Start the game with the `-novr` Launch Option, go change SSAO to 'Off', and then restart without -novr. I tried my best to make SSAO automatically turn off, but sometimes it stays on somehow.

**Comment by baggyg** [comment]
Yep, that was it. Thanks for your assistance. So basically working perfectly now with any SS setting. 

Maybe worth noting if someone has the same problem: I couldn't actually launch on the desktop because I still had the old Rift DK2 setting in ENGINE_SETTINGS.XML. Removed that and then ran fine on desktop, and then again in VR after I had removed the -novr tag

**Comment by Ratasan64** [comment]
Can this be reopened? It's a reocurring issue, even with SSAO set to "off". It happens when supersampling above 1.3, lightning differences between each eye becomes visible.. Is there **ANY** way to fix this by tweaking the enigne settings?
