### ISSUE TITLE
Vive crash on startup

### ISSUE THREAD

**Issue by irvinekyle** [Nibre/MotherVR#38]
Tried all the other advice; disabled in game VR theater, changed to windowed mode, boots fine with -novr flag, but -steamvr looks to start and then immediately crashes.  Can send logs if you want?  Here's hoping it's just a bug.

**Comment by irvinekyle** [comment]
ok got it loading finally ... for me it was the resolution in the windowed mode.   Had to make it something friendly, like 1920x1080 and after that it worked like a charm.  Still had a crash in game around the intro part, but i had enough of a taste to make this well worth the effort. 

 I found that using the gamepad for forward, backward and strafing left/right worked for me, and just physically turn/yaw the direction you want to go.  Have to say that this game with true motion tracked controllers would just be insane.  Kudos Nibre ... a peek into the future i'd say!

**Comment by JulsIII** [comment]
same problem, but this fix doesn't work for me.

**Comment by JulsIII** [comment]
Still an issue - non of the listed fixes in the issues sections work for me.
