### ISSUE TITLE
Vive crash on startup

### ISSUE THREAD

**Issue by dalex32** [Nibre/MotherVR#39]
![error](https://user-images.githubusercontent.com/19300258/29755623-581e2f3a-8b60-11e7-8ff3-ec213c1ce1f4.png)

**Comment by Esge71** [comment]
I've got exactly the same issue. I tried typing "-openvr" into the Launch options but still get the same crash. Using Vive with all the latest drivers etc. 

I can't see anything to change the OVR detection.

**Comment by Esge71** [comment]
Had exactly the same issue.

Tried "-steamvr" in the Launch Options under properties and got it to launch but I can't get the position of the headset to reset! ><

**Comment by Nibre** [comment]
This is because you aren't setting `-steamvr` under the Launch Options, like Esge71 said.
