### ISSUE TITLE
Alpha 0.3.0.1 Hotfix & Alpha 0.3.0 not working on OR CV1

### ISSUE THREAD

**Issue by huliqan** [Nibre/MotherVR#40]
Alpha 0.3.0.1 Hotfix & Alpha 0.3.0 not working on OR CV1 in win 7x64(works only in win 10)
1.with dxgi.dll only
![default](https://user-images.githubusercontent.com/11330258/29755665-f0485fd6-8ba3-11e7-9254-7691935c167a.jpg)
2.with dxgi.dll & openvr_api.dll
![2](https://user-images.githubusercontent.com/11330258/29755698-60bd46fa-8ba4-11e7-8645-ccc7041c84bd.jpg)
![3](https://user-images.githubusercontent.com/11330258/29755701-63ec23a0-8ba4-11e7-90ad-1f3c7589d9f8.jpg)
Alpha 0.2.0 with " -disableblinders" working fine!!! in win 7x64 !!!

**Comment by Nibre** [comment]
So it's only on 7x64 you're having this issue? It's not happening on Windows 10?

**Comment by danielrid** [comment]
I can confirm this is also happening on Windows 10. (0.3.0-0.3.1)
Oculus will only run in SteamVR mode (/steamvr), copying only DXGI.dll complains about OpenVR.dll missing, must be copied as well.

**Comment by huliqan** [comment]
_<<So it's only on 7x64 you're having this issue? It's not happening on Windows 10?>>_
Yes!Only win7x64 issue.On win 10 works good!
--------------------
### 

_<<If you want to dynamically load it the easiest solution is to wrap the entire openvr functionality that you are using in a separate dll and dynamically load that.>>_
How can i do it?

**Comment by huliqan** [comment]
<<So it's only on 7x64 you're having this issue? It's not happening on Windows 10?>> Yes!Only win7x64 issue.On win 10 works good!
 --------------------   
<<If you want to dynamically load it the easiest solution is to wrap the entire openvr functionality that you are using in a separate dll and dynamically load that.>>
 How can i do it?

**Comment by huliqan** [comment]
So it's only on 7x64 you're having this issue? It's not happening on Windows 10?
 Yes!Only win7x64 issue.On win 10 works good!
 --------------------   
If you want to dynamically load it the easiest solution is to wrap the entire openvr functionality that you are using in a separate dll and dynamically load that.
 How can i do it?

**Comment by xiaoguid** [comment]
Huliqan: My comment was addressed to **Nibre** to suggest how he can fix the issues. Thanks.

**Comment by Nibre** [comment]
Can you try again with the latest release? It should possibly be fixed, and if not, it will at least give me a more descriptive error message to work with.

**Comment by huliqan** [comment]
Thank you very much for the new release Alpha 0.4.0 !!!
Testing...

**Comment by huliqan** [comment]
Everything works just fine !!! win7 & win10 perfect!

**Comment by huliqan** [comment]
Can you make a script like here https://www.reddit.com/r/oculus/comments/7h6nva/smooth_locomotion_in_doomvfr_for_rift_i_scripted/
but for all the xbox joy buttons?
With script for DOOM , Alien Isolation works with left touch like left stick xbox-joy

**Comment by n00bster1337** [comment]
This would be the best thing ever! Someone cleverer than me please do this!

**Comment by Nibre** [comment]
No need for a script, I'll be adding Touch support directly into the mod

**Comment by Nibre** [comment]
Also, SSAO is fully disabled now because it doesn't function correctly in VR. Setting it to 'Standard' has stereo issues, where lighting will look different in each eye, and 'HDAO' destroys the VR rendering entirely so you can't see anything. Better to just not have it, than have it accidentally cause people problems.

**Comment by huliqan** [comment]
SSAO-understood!
For touch-emulation - I rebinding the script, but could not add mouse buttons and mouse rotations
https://drive.google.com/file/d/1TljlKn7dQ9wRqDv1zRR8O0H2FOkeriDH/view?usp=sharing

**Comment by huliqan** [comment]
add to input.cfg(saves folder 214490)
bind LEFT turn_left
bind RIGHT turn_right
or replace it with mine from the archive
and run script
from archive https://drive.google.com/file/d/1TljlKn7dQ9wRqDv1zRR8O0H2FOkeriDH/view?usp=sharing

**Comment by huliqan** [comment]
https://drive.google.com/file/d/12oh4jxhKfNXWp2Tx9uotvmbfGI0n13Vv/view?usp=sharing
full script with mouse look and without(on keyboard arrow)
