### ISSUE TITLE
Graphics settings reset by themselves.

### ISSUE THREAD

**Issue by jonnypanic** [Nibre/MotherVR#41]
I am not entirely sure if this is a problem with MotherVR or the base game, but when I restart, certain graphics settings always turn themselves back on. I always have to disable AO every time I load the game. 
Not a big issue though. Thanks, it is a really great mod.

**Comment by MulleredOG** [comment]
it's always done this, even in the original DK2 implementation

**Comment by Nibre** [comment]
As far as I can tell, AO should be disabled regardless of what the settings says. Both 'Standard' and 'HDAO' cause graphical issues, so I bypass them and disable them anyway.

**Comment by jonnypanic** [comment]
I think the setting is doing something. I can see the AO effect on shadows and get a decent performance boost disabling it. Other settings reset too, shadow maps is stuck on 512, volumetric lighting is off. Is that intentional? Any way to force the graphics settings to stick? Cheers.

**Comment by Nibre** [comment]
It's the original VR support that's doing it, or maybe just the standard game adjusting itself. Nothing I'm going affects those settings, and having any sort of AO on causes problems in VR.

**Comment by Nibre** [comment]
This should be fixed in the latest release. Settings that don't affect VR should no longer automatically change on their own, and ones that do affect VR (like SSAO) will be forced off and hidden from the settings menu.

Just let me know if you still have issues with this on the new version.

**Comment by jonnypanic** [comment]
Just tried it out, and yeah it now just seems to work perfectly. Graphics settings haven't reset, and the game looks amazing. Thanks a lot.
