### ISSUE TITLE
Left and right eye out of alignment on Vive

### ISSUE THREAD

**Issue by seanyc123** [Nibre/MotherVR#42]
There's a big bar in the middle and I don't see in 3D I see two clashing warped perspectives in each eye.
Edit: think I'm having same problem as this guy https://github.com/Nibre/MotherVR/issues/17 but my files are 100% verified

**Comment by Nibre** [comment]
That's because your SSAO is set to 'HDAO'. Start the game with the `-novr` Launch Option, go change SSAO to 'Off', and then restart without `-novr`. I tried my best to make SSAO automatically turn off, but for like 1 in 200 people it stays on somehow.

**Comment by seanyc123** [comment]
Will try that now, thank you very much for your quick response.
