### ISSUE TITLE
Game wont show up on desktop

### ISSUE THREAD

**Issue by Masamune1018** [Nibre/MotherVR#43]
Yeah, i can only see the game on my oculus, and im trying to record xd

**Comment by Nibre** [comment]
From the release notes;
```Game window will show solid black, even though the game does show in the headset. You can use OculusMirror.exe for watching/recording with in the meantime (located in Oculus\Support\oculus-diagnostics), or Display Mirror if you're using SteamVR.```

**Comment by Masamune1018** [comment]
alright thx! :D

**Comment by petrhipik** [comment]
And if i have HTC VIVE? What then?
