### ISSUE TITLE
Font is very small

### ISSUE THREAD

**Issue by dafaithz81** [Nibre/MotherVR#47]
Some things are impossible to read, cause its simply to small.

**Comment by skipperoni** [comment]
I'm finding that quick time events are hard too, like when you're being attacked by a working joe. Is there any way to make the QTE more prominent to make it easier? Thanks!

**Comment by dafaithz81** [comment]
Ye, i think when u know alien isolation you can imagine most of the stuff, but im a fresh player that have bought it especially for this great mod and ive no clue how to craft things etc. 
And i cant read it, cause its simply not readable.

**Comment by Aesop112** [comment]
Is there a config file to adjust that?

**Comment by Nibre** [comment]
It's mostly a Vive problem, the FOV/Resolution tradeoff it has isn't super favorable towards text. Text will be made larger soon

**Comment by Nibre** [comment]
This should be mostly resolved in this newest release. I've made text+UI elements much larger, at least as much as I can without getting so crazy that everything is overlapping. Exception being the Weapon/Crafting menu, as it has other problems that need to be worked on.

It should be much better now, or at least as good as I can get it for the time being. I'll go ahead and close this issue, but feel free to let me know what you think of the adjustments.
