### ISSUE TITLE
[Alpha 0.3.0.1] Mouse Behavior Question

### ISSUE THREAD

**Issue by xXRedQueenXx** [Nibre/MotherVR#50]
Hi Nibre,

While sitting down to take an initial playtest of your mod today on my Vive (playing with M+KB), I noticed that you only seem to be able to mouselook left and right -- looking up and down seems to be controlled solely by the HMD orientation.  I'm curious, is this behavior intentional?  If so, could it be possible to toggle full mouselook freedom, perhaps with a launch option?

I ask because so far the only thing that has a shot of inducing simsickness in me while playing seated is restricted mouselook.  Having both the HMD and the mouse able to control my view doesn't bother me at all, VorpX permits this and it's perfectly comfortable to me.  (I even like to use my head in tandem with the mouse when making fast turns and looking around sometimes!)

Anyway, it was just a bit of behavior I didn't expect, and thought I would ask.  Otherwise, it's looking good so far, and I saw from some of your other comments you're already working on a fix for the font size, so nothing else to flag to you at this time.

Thank you so much for bringing A:I to VR, I'd been dying to play it this way for ages, and I'm looking forward to the next update!

-Best,
Red.Queen

**Comment by Nibre** [comment]
This look behavior is forced by the game, they made it that way when they attempted VR support originally. So it's not anything specific that I've modified or added.
