### ISSUE TITLE
Space between eyes

### ISSUE THREAD

**Issue by EvilPanda666** [Nibre/MotherVR#52]
I just loaded it up and I'm able to get it running but there's about a 2 inch wide grey bar between my eyes when looking into the HMD and everything is a little skewed. Have you run across this?

**Comment by xXRedQueenXx** [comment]
When you say everything is a "little skewed", is it kind of like you see almost the same image in each eye, but shifted?  And the gap between the left and right eye is the grey bar?

If that sounds somewhat like what you're seeing, there's an easy fix -- temporarily uninstall the mod, then launch A:I.  Go to your video options in the game, and set SSAO to Off (there's a conflict between this mod and ambient occlusion) and save your updated video options.  Quit back out of the game.  Then you can put the mod back and it should be ok now.

**Comment by d0x360** [comment]
Interesting... I play with ambient occulsion on and I've never seen it after 2 runs through the game.

**Comment by Nibre** [comment]
This should be fixed now, it now forces SSAO to Off (which is what was causing the issue).

Give it a try, and just let me know if it's still happening for some reason.
