### ISSUE TITLE
Vive Crash at Start - FIXED! PSA for RAZER Owners!

### ISSUE THREAD

**Issue by JulsIII** [Nibre/MotherVR#55]
No listed solutions here have worked. On windows 7 using vive - no issues with any other games or vr mod games. Open to any suggestions for a fix! 

FIXED:  PSA! PSA! If you use RAZER products and have Razor services running you may suffer seemingly unsolvable crashing at startup. I disabled ALL Razer software and services and BAMO! Works just fine now. I don't know WHY this is happening - but if it's happening to you try disabling RAZER software. Worked for me.

**Comment by Nibre** [comment]
Does this crash still happen on the newer version, if you have that software enabled? If it is, can you try getting me a [crashdump](https://github.com/Nibre/MotherVR/issues/35#issuecomment-325194659), so I can try and figure out what's causing it.

**Comment by NeonUniverse** [comment]
Just a follow-up to this, I have tested this out myself and found that Razer Synapse is creating the issue, no other apps from Razer cause any issue.
