### ISSUE TITLE
Crash, if not started at least once before using VR

### ISSUE THREAD

**Issue by Beaneater76** [Nibre/MotherVR#6]
Alpha 0.11

I have installed AI freshly and pasted the dll to the AI directory. Upon starting the game crashed. Starting the game at least once and setting things up before playing in VR solved the issue.

So be aware to start at least once after a fresh install without VR.

Josef

**Comment by lewisco** [comment]
Weird, I downloaded the game fresh from Steam and launched it with the dll for the first time and was able to start a new game with no issues.

**Comment by Beaneater76** [comment]
Hmm, maybe there was some further influence in combination. But as a hint, it might help somebody if the game crashes at the initial run.

**Comment by panterpansn** [comment]
I got the issue also. Directly after starting the game crashes

**Comment by BlaineMiller1988** [comment]
I have the problem and found the solution until it is fixed in the next release.  You just have to go into the config file ALI123 where the DLC list is put.   You have to change the last line like this: 

[Options]
UseSavesBackup = 1.

After you have done this save the file and the problem goes away and it boots every time without crash.  Please fix this!

**Comment by panterpansn** [comment]
@BlaineMiller1988 
Where is this File located?

**Comment by BlaineMiller1988** [comment]
Same one as the executable for me.

**Comment by panterpansn** [comment]
so you mean 
X:\SteamLibrary\steamapps\common\Alien Isolation

**Comment by BlaineMiller1988** [comment]
@panterpansn I was wrong.  It still crashes.

**Comment by panterpansn** [comment]
now i got the menu once but it still crashes. perhaps something like an hardware incompatible

**Comment by Nibre** [comment]
This should be fixed in the latest release. So give it a try and let me know.
