### ISSUE TITLE
Interaction with terminals, save stations, etc turn the head around

### ISSUE THREAD

**Issue by nlooije** [Nibre/MotherVR#62]
Hi, great mod! Love you work!

I noticed that when i interact with any terminals or save stations and the like, my head is turned around 180 degrees. I need to turn around 180 degrees to see the terminal.

Any fix for this?

**Comment by Deiru2k** [comment]
Same problem here.

**Comment by MrCK1** [comment]
Never happened to me, are you using a Rift or Vive?

**Comment by JoshWobbles** [comment]
I've seen this happen a lot when I am playing racing sims and the room is set up backwards or the HMD is backwards on launch. Try setting up your room again making sure to configure the "front".

**Comment by tkapis** [comment]
This is because you have physically turned during the game and are no longer facing your front direction according to playspace set-up. You must be facing to the front according to your set-up when you use those things.

**Comment by Nibre** [comment]
This is fixed in the latest [Release](https://github.com/Nibre/MotherVR/releases)
