### ISSUE TITLE
XBOX 360 wireless pad not working with mod. [SOLVED]

### ISSUE THREAD

**Issue by m7cky** [Nibre/MotherVR#63]
When I launch the game with the mod my xbox controller is not recognised in game.
When I remove the dll from the install & launch without VR controller is fine.

**Comment by datBoiMoudi** [comment]
I got the same issue.

**Comment by blord86** [comment]
¿Have you got Steam Big Picture running? If you have, disable controller on Big Picture settings, or exit Big Picture before starting the game with the mod. I launch the game from Oculus Home and have zero problems with my Xbox controller.

**Comment by m7cky** [comment]
I wasn't running big picture but am launching from Steam.
You were dead right though, disabling controller has fixed my issue!
Thanks dude!
