### ISSUE TITLE
[Alpha 0.4] Dialogs won't trigger (Game breaking)

### ISSUE THREAD

**Issue by glequeux** [Nibre/MotherVR#66]
Hello,
This is the first time I try this mod and this is really promising ! Thx !
Unfortunately I couldn't go really far in the game due to the fact that sometimes NPC won't start dialogs :(

My first run wen't fine until I had to talk to the guy in the medical center, He didn't seem to notice me, I was not dressed, then I got to the cafeteria, talked to the girl, got to my room, got dressed, then came back to the medical lab. Still no reaction from the NPC.

I started a new game, noticed that UI (lifebar) didn't follow me anymore, just teleport when I press start. Dressed up, talk to the cafeteria girl, got to the medical lab, this time the guy talked to me, I followed him to the main deck and then again, the dialog with the captain did not trigger :(

I run on Oculus retail, W10, with ultra settings on a 1080Ti playing with XBox one pad.

**Comment by Nibre** [comment]
Let me know if you're still having these issues on the latest [Release](https://github.com/Nibre/MotherVR/releases)
