### ISSUE TITLE
Opens on desktop but not rift

### ISSUE THREAD

**Issue by duig0** [Nibre/MotherVR#7]
Hiya,

The game opens windowed on pc screen but nothing on rift. Rift stays in oculus home and no headmovements are translated to the game....any ideas?

Thanks in advance :-)

**Comment by lumbbumba** [comment]
Same here. Game opens only in desktop mode and not on my DK2. Do you need more to run this on the RIFT? Any config changes or something?

**Comment by stephenbdavies** [comment]
I'm also having this issue.  Using a CV1, launching from within steam.

**Comment by duig0** [comment]
Small update - if i have the rift off when starting the game, then it loads on desktop without picture, with sound - rift is still blank....HOWEVER if i ALT-TAB out of alien isolation and go back in i get picture in the Rift Yyyyyeeeaahhh.....BUT....it crashes within mere moments.....so, still not working for me but a little progress at least

**Comment by duig0** [comment]
Another update...using the alt-tab method with headset off, mentioned  above i can view into movies, then i get the hourglass in the rift, can see the chaporone (couldnt before) and then....BOOM....crash

If i wear the hmd when starting in steam i get the following

"Fatal error steam client needs to be running to play this game"

If i remove the .dll or use the -novr in launch options the game loads as normal...... damn....so close, yet so far

**Comment by duig0** [comment]
*intro movies

**Comment by lumbbumba** [comment]
I tried your method but it does not help. I cant see even videos. Do you see the intro in the RIFT too?

**Comment by duig0** [comment]
Yes but only if i am not wearing the headset when it starts, when i hear the fox music i alt-tab out of aluen isolation and back in again. Then it shows up in the rift...but crashes after the inteo videos sadly

**Comment by duig0** [comment]
Of im wearing the headset when it starts i only get oculus home in the rift and after a few moments the game crashes on desktop with the steam error listed above....i think Steam doesnt like the .dll on my system for somw reason....over the last few days i uninstalled oculus runtime, alien isolation, and steam and reinstalled....same issue :-(

**Comment by lumbbumba** [comment]
@dui0 do you have twitter or something else where I can contact u? I can not send pms in github.

**Comment by duig0** [comment]
No twitter im afraid....i have a Reddit account under the same name though...you can pm on Reddit i believe

**Comment by duig0** [comment]
Oops...my bad the Reddit account i.d du1g0.....

**Comment by Lurkstrober** [comment]
Have you tried making sure that SteamVR is started before starting Alien Isolation? I had a similar sounding problem when I first tried out the mod. I started up AI and could hear it, but nothing displayed in the Rift. I noticed that SteamVR had not started automatically and thought it might be related.

After that I made sure that SteamVR had started and tried again. The image displayed properly in the Rift and it's been working great guns since then.

Hope this helps! :)

**Comment by lumbbumba** [comment]
@duig0 check your reddit

**Comment by baggyg** [comment]
@Lurkstrober AI uses a native Oculus SDK integration and therefore should not require SteamVR at all. I suspect you may have fixed it another way and wrongly attributed the solution to SteamVR

**Comment by duig0** [comment]
I tend to agree....i tried as suggested, however....but no dice
unfortunatly

**Comment by baggyg** [comment]
I'm not sure if this is clarified by @Nibre... in the original version you had to alter the ENGINE_SETTINGS.XML file to turn on the support. I suspect a lot of people still have this setting saved. It may be worth trying this just to see if this forces it to the rift. 

Basically the first part from here: http://www.makeuseof.com/tag/enable-oculus-rift-mode-alien-isolation/

It could well be that Nibre, patched around this although I don't remember directly reading about it. Certainly my xml file still has this setting

**Comment by Lurkstrober** [comment]
I think you're right Baggyg. I just checked running it directly from Oculus Home (1.17 dropped for me yesterday) and it started up with no sign of SteamVR anywhere. Sorry to put you on the wrong track their duig0.

**Comment by duig0** [comment]
No worries mate, i do appreaciate the gesture though :-)

**Comment by Nibre** [comment]
Are you guys still having these problems with the latest release?

**Comment by Nibre** [comment]
I'll close this for now, but you can still respond if you need to.

**Comment by duig0** [comment]
Works great now. ....thank you Nibre you are a god amoungst Modders
