### ISSUE TITLE
"Mash" button prompts too small to see

### ISSUE THREAD

**Issue by JoshWobbles** [Nibre/MotherVR#70]
It looks like most normal press prompts have been enlarged for VR readability, but the "mash" ones still appear to be very small. Example when fighting off a synth that has you in their grips or starting a generator.

**Comment by NeonUniverse** [comment]
Possible that the way the game itself scales them, it doesn't like the fact the mod up-scales them so it defaults to the normal ones. Could also just be a case that they are a separate file that still needs to be up-scaled, but I honestly have no clue.

**Comment by Nibre** [comment]
I think that I've fully fixed this in the newest [Release](https://github.com/Nibre/MotherVR/releases)
