### ISSUE TITLE
Crash on startup.

### ISSUE THREAD

**Issue by Nordomus** [Nibre/MotherVR#72]
I've copied dxgi.dll file into game directory, added -steamvr into launch options and I got this error:
"Failed to initialize SteamVR!
[Another app was already launching (117)]

Make sure the SteamVR is installed correctly, and try again. If you aneed to temporarily disable MotherVR, you can launch the game with the '-novr' parameter.

MotherVR (and Alien: Isolation) will now exit."

**Comment by erik-smit** [comment]
I'm having the same problem.
I think it's due to "SteamVR Desktop Game Theatre" starting at the same time.

**Comment by JoshWobbles** [comment]
@erik-smit did you remember to add the -steamvr command line switch?

**Comment by erik-smit** [comment]
Yes.

**Comment by erik-smit** [comment]
Ahh, I probably just had to be patient at this point!
The game seems to work now!

**Comment by Nibre** [comment]
Yup, it was the Game Theatre causing issues. There are better checks for that now, so if it's causing problems, it will tell you to disable them in an alert. Glad to hear you got it working!
