### ISSUE TITLE
ReVive

### ISSUE THREAD

**Issue by Tyrminaotr** [Nibre/MotherVR#8]
Can I use it with Vive using ReVive?

**Comment by otraupe** [comment]
Tried this already?

https://www.vrheads.com/how-launch-your-steamvr-games-oculus-home

I didn't, so far.

**Comment by otraupe** [comment]
Ok, so although this is said to only work with SteamVR titles (and AI is not, even with this mod, to my mind), this might perhaps work.

You have to opt in to the open test channel of oculus home (settings -> beta). Then you will download an update of OH. And after installation, once you open a SteamVR title the regular way, it also appears in OH, even with an icon.

I just tried this with AI, and it does (!) appear in OC, and can even be run from there. Now it remains to be seen, whether it works that way with Revive.

**Comment by otraupe** [comment]
Nope, not starting.

**Comment by Nibre** [comment]
Vive support is now on this newest release. Use -steamvr to enable it.
