### ISSUE TITLE
alien  isolation fault 

### ISSUE THREAD

**Issue by henas0** [Nibre/MotherVR#81]

**Comment by henas0** [comment]
hi guys im using wmr dell ive just purchased the alien isolation and the mother vr but when i try load it says unable to load oculus is this just for oculus and cant i play in steam ??

**Comment by NeonUniverse** [comment]
Make sure all files are in the right places before trying again. Also make sure al Oculas Rift Drivers are up to date

**Comment by blord86** [comment]
With a WMR headset you don't need any Oculus drivers at all. Try to launch the game with the parameter -steamvr to force SteamVR mode instead of Oculus, that should do the trick if you have your headset correctly setup for SteamVR.

**Comment by henas0** [comment]
decided to get a refund in the end off steam as the messing about i was expecting a good experience but just got dramas which wasn't why i built a high end pc to play vr :(

**Comment by JoshWobbles** [comment]
There is no drama, it’s quite simple, actually one of the easieast 3rd party experiences I have ever had. You jumped the gun on the refund far too fast because you just gave up on what is still my favorite VR game and I have nearly all of them.

**Comment by Nibre** [comment]
There is a new [Release](https://github.com/Nibre/MotherVR/releases) now. If you decide to try the game again in the future, feel free to respond to this issue and re-open it, if you happen to have similar issues
