### ISSUE TITLE
Smooth turn hidden in readme

### ISSUE THREAD

**Issue by cercata** [Nibre/MotherVR#84]
Sorry, didn't see how to disable it

Anyway, you changed default behaviour, and people who don't need snap turn, will skip that section when reading the notes ... I guess many people will have the same initial reaction than me

**Comment by cercata** [comment]
I already did. I see you only read the subject
I'm just giving feedback to the DEVs to improve the DOCs.

People normally don't read the details of options they don't like in the readme.
So people with full virtual legs, will read "Snap turn", and will skip that section, wo once in the game, they will not know how to turn it off

**Comment by blord86** [comment]
The option will probably be implemented into the MotherVR menu inside the game once it's enabled in future versions. Right now it's better that snap turn is enabled by default. People used to smooth locomotion will read the release notes and find out how easy is to disable snap turning. Better to use a default option that won't make some people sick. Yeah, It would be better to have a command line option to permanently disable it, but I can live with clicking LT + RT + RS every time I enter the game.

**Comment by cercata** [comment]
@blord86 Nobody reads me ?

I'm just asking to give visibility on how to enable smooth turn, since people with full virtual legs will skip the "Snap turn" section of the readme !!!!

**Comment by blord86** [comment]
Now that you changed the thread title I read you. I agree, the readme could be rewritten.

**Comment by cercata** [comment]
Yeah, I realized people awswers without the posts ...

**Comment by JoshWobbles** [comment]
I read your original post, but then you changed it, soooooo.....

**Comment by cercata** [comment]
Weird, I edited it 10 mins after writing it ...

**Comment by Nibre** [comment]
Lol, the irony of you saying people should read posts. But yea, you can turn the Snapturn off, like they said. I'm going to be updating the main page of the Repo soon with more information, so it's not all left in the individual release notes.

**Comment by cercata** [comment]
It's not the same answering to something without reading the 3 lines of the post, that skipping a section of something that really doesn't interest you in a long readme.

If you think it's the same, let it hidden there :P

**Comment by Nibre** [comment]
I intentionally made it the very first item on the list. It looks like everyone else who were wondering if there was a way to disable it, either read it the first time, or thought 'Maybe that Snapturn section will tell me more about how to deal with Snapturn'.

But it's all good, dude. Thank you for editing the post. I think the others were just off put by the derisiveness that it initially had.

**Comment by cercata** [comment]
"the industry" is makeng many games without smooth turn, because they are afraid of people getting sick.
And we have to rant often so the include it in games.

So many of us we just get sick only of hearing "snap turn". 
I was eager to try it, but even with eagerness I read quickly the release notes, except the Snap turn section.

And when I tryed the MOD, the first thing I though it's that you had removed smooth turn because some people said they got sick with it ...

**Comment by Nibre** [comment]
I've now added this information to the included `readme.txt` with the download (so it's not just the release notes).
