### ISSUE TITLE
launch error wrong heaset 

### ISSUE THREAD

**Issue by yohaskan** [Nibre/MotherVR#86]
At launch, I failed because I do not have an Oculus headset (Obviously since I have HTC Vive)

**Comment by Nibre** [comment]
You'll need to add `-steamvr` to the game Launch Options in Steam

**Comment by Nibre** [comment]
I've updated the included `readme.txt` that's included with the download, to include this information. Feel free to respond to this if you're still having issues getting it to work with SteamVR
