### ISSUE TITLE
Terminals have locked positional tracking

### ISSUE THREAD

**Issue by Clodo76** [Nibre/MotherVR#9]
I don't find this issue in the 'Known Issues (that are being worked on)' release log.

In some situation, for example when using terminals, the distance between head/camera and the terminal it's fixed/forced.
Using any terminal it's too close, but the real problem is positional tracking (moving back my head) don't work.
I hope you can resolve it. No other issue in the mean-time, thx for MotherVR, i'm waiting this since DK2 version years ago. I just made a donation for your effort. Thx again.

**Comment by cercata** [comment]
That was my main problem when playing it with DK2 native support !!!

If he can fix it, it will be awesome !!!!!

**Comment by bakman2** [comment]
>Interactive objects position you a little too closely, so it can be hard to focus on them. For now, closing one eye, or temporarily adjusting the IPD downward, can help.

**Comment by Donkeyfumbler** [comment]
Excited to see a new an update but then disappointed to see that this is still a problem - it's stopping me playing the game at the moment as it makes me feel ill. 
Nibre, are you able to say whether this is something you will be able to fix eventually, even if it's not for some time? Or is it impossible to do?

**Comment by Donkeyfumbler** [comment]
Would really like to know if this is likely to be fixed or if it isn't possible please? if it is possible then I'll wait and play it in VR later but if it isn't then I'll probably play it now as a normal game - please can you just give me a heads up. Thanks.

**Comment by cercata** [comment]
@Donkeyfumbler I'm like you, waiting for this to play the game.
No rush, but it's not gonna be fixed, I'll play the game now ... before we have hundreds of AAA VR games this holyday xD

**Comment by Donkeyfumbler** [comment]
Thing is I was really enjoying it up to the point where I started using the terminals and I would be happy to wait until it was fixed, even if it takes a while to do it. If it's just not possible though (and if it's not then that's fine - no criticism here from me), I'd like to carry on playing it now in regular 2D. It's just frustrating that having asked several times both here and in other places (Reddit, Twitter) @Nibre doesn't seem to want to give any indication at all about this (unlike other things like the turning which he is happy to talk about). I realise he owes no-one anything, but a simple 'Yes I think it can be fixed and I intend to try at some point' or 'No I don't think it can't be done' is all I'm after.

**Comment by Nibre** [comment]
Yes it can be fixed (have been able to figure where the problem lies) and I'm currently working on it

**Comment by cercata** [comment]
Awesome !!!!

I'm one of those people who can feel 100% Immersion while playing VR with the Xbox controller, so this is gonna be totally awesome !!!!!!

I have already beaten the game on TV, it was good, but that is on another league !!!!

**Comment by Donkeyfumbler** [comment]
Perfect - thanks very much for letting us know. In that case I'm happy to wait until you have it done, regardless of how long it takes.

**Comment by cercata** [comment]
@Donkeyfumbler 

[https://twitter.com/nibre_/status/1005230149061697538?s=09](url)

**Comment by Donkeyfumbler** [comment]
@Nibre. Awesome - so as long as it takes wasn't very long at all :)

**Comment by Nibre** [comment]
This has been fixed in the latest [Release](https://github.com/Nibre/MotherVR/releases) 😎
