### ISSUE TITLE
Error at launching Alien in VR

### ISSUE THREAD

**Issue by tcb133** [Nibre/MotherVR#96]
Hi! I have a no-steam version of it ant i'm having trouble starting the app. It shows this message: 
Exe check failed!
[0x54254411]

This check is to ensure that MotherVR is correctly modifying the game, and is looking in the correct locations.

If Alien: Isolation is on an out-dated version, make sure to update through Steam. If a new update to the game has just been released, or this check failed for some other reason, MotherVR may need to be updated. 

MotherVR will now be disabled, and Alien: Isolation will startup normally.

Any clues? 
Thanks.

**Comment by Khiu** [comment]
Looks like you have the wrong version of the game installed.

**Comment by Nibre** [comment]
Only the most up-to-date version of Alien: Isolation is supported, which was last updated in 2015

**Comment by Nerdherdx** [comment]
Did you find a fix?
